version: '3.8'
services:
  app:
    image: rconfig/rconfigv6:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./data/.env:/var/www/html/rconfig/.env  # Mount the .env file from local disk to container
      - ./data/storage:/var/www/html/rconfig/storage  # Mount app storage directory to host directory

  db:
    image: mysql:8
    env_file: ./data/.env  # Use env_file to specify environment variables for DB
    ports:
      - "3306:3306"
    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5 -e MYSQL_ROOT_PASSWORD=xxx -e MYSQL_USER=xxx -e MYSQL_PASSWORD=xxx -e MYSQL_DATABASE=xxx --entrypoint sh mysql:8 -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
    volumes:
      - ./data/db_data:/var/lib/mysql  # Mount MySQL data to host directory
 
volumes:
  db_data:

networks:
  rconfig_network:

